In [15]:
import numpy as np

def convolution_2d(X, W, p=(0,0), s=(1,1)):
    W_r = np.array(W)[::-1, ::-1] # rotate filter vertically and horizontally
    X_orig = np.array(X)
    
    # sized of padded X
    n1 = X_orig.shape[0] + 2*p[0]
    n2 = X_orig.shape[1] + 2*p[1]
    
    X_padded = np.zeros((n1, n2))
    X_padded[p[0]:p[0]+X_orig.shape[0], p[1]:p[1]+X_orig.shape[1]] = X_orig
    
    Y = []
    
    times_conv_h = int(((X_padded.shape[0] - W_r.shape[0]) / s[0])+1)
    times_conv_v = int(((X_padded.shape[1] - W_r.shape[1]) / s[1])+1)
    
    for i in range(0, times_conv_h, s[0]):
        Y_i = []
        for j in range(0, times_conv_v, s[1]):
            # take square of kernel size
            X_sub = X_padded[i:i+W_r.shape[0], j:j+W_r.shape[1]]
            Y_ij = np.sum(X_sub * W_r, axis=(0,1))
            Y_i.append(Y_ij)
        Y.append(Y_i)
            
    return np.array(Y)

In [16]:
X = [[1, 3, 2, 4], [5, 6, 1, 3], [1, 2, 0, 2], [3, 4, 3, 2]]
W = [[1, 0, 3], [1, 2, 1], [0, 1, 1]]

print(convolution_2d(X, W, p=(1,1), s=(1,1)))

[[11. 25. 32. 13.]
 [19. 25. 24. 13.]
 [13. 28. 25. 17.]
 [11. 17. 14.  9.]]


In [18]:
import scipy

print(scipy.signal.convolve2d(X, W, mode='same'))

[[11 25 32 13]
 [19 25 24 13]
 [13 28 25 17]
 [11 17 14  9]]
